resources:
  - url: http://127.0.0.1:5000/clock-weather-card.js
    type: module
views:
  - cards:
      - type: custom:clock-weather-card
        name: Clock Weather Card Development
        entity: sun.sun
        test_gui: true
