name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Build the file
        run: |
          cd /home/runner/work/clock-weather-card/clock-weather-card
          yarn install
          yarn build

      - name: Package release zip
        run: |
          cd /home/runner/work/clock-weather-card/clock-weather-card/dist
          zip clock-weather-card.zip clock-weather-card.js animated-icons.js

      - name: Upload zip to release
        uses: svenstaro/upload-release-action@v1-release
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/clock-weather-card/clock-weather-card/dist/clock-weather-card.zip
          asset_name: clock-weather-card.zip
          tag: ${{ github.ref }}
          overwrite: true

      - name: Verify HACS compliance
        uses: hacs/action@main
        with:
          category: plugin
