name: Release

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  release:
    name: Prepare release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Build the file
        run: |
          yarn install
          yarn build

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: dist/clock-weather-card.js