name: Static Checks

on:
  push:
  pull_request:

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  verify:
    name: Build & Lint
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: lts/*

    - name: Enable Corepack
      run: corepack enable

    - name: Install dependencies
      run: yarn install

    - name: Lint
      run: yarn lint

    - name: Build
      run: yarn build
